### PR TITLE
WIP: add a Beacon client

### PR DESCRIPTION
**Pull request by MaxKellermann**
Last week, I started a project to share live GPS locations while riding on my bike (to let my wife know that I havn't crashed just yet): https://github.com/MaxKellermann/beacon
That project is in early development (copying some code I've written for an app called "XCSoar" for glider pilots https://github.com/XCSoar/XCSoar/ and this is how it looks like on the web: https://skylines.aero/tracking).

After I've switched from the oh-so-ugly Strava app to AAT, I want AAT to be the client for my new service. I believe in "release early, release often", so here I'm submitting a very rough draft of my code to you. This is obviously not ready for merging, it just barely works, has no code comments, no way to switch it on and off, no configuration interface, hard-codes a server IP address and so on.

But I'd like your opinion on my idea and maybe hints on how to integrate it properly into AAT. Eventually, this will turn into something that can be merged. Or maybe it stays in my fork forever, depending on whether you say "yay, some day" or "nay, never".

### CODE REVIEW

**Comment by bailuk** [comment]
I've just glanced trough your code. 

Some remarks and questions:

- It's a cool feature that looks promising and I look forward on having it integrated into AAT.
- As you already mentioned, I can't merge this request for security and privacy reasons: It must be disabled by default and it must be clear to the end user that his location gets sent to a server. It also must be clear who can access his location information and how it can be accessed.
- Generally it's well integrated (by correctly using `VirtualService` and `ContentSource`).
- What use will `BeaconSource` have? Right now it only copies `CurrentLocationSource`
- How will the users location and/or track be accessible? Trough a web interface or inside the MapView?
- Protocol specif code needs some documentation: not everyone knows what CRC is and how it is used.
- `client = new BeaconClient(new InetSocketAddress("138.201.185.127", 5598));`  
Use constants for the server address and the port number and place them at the beginning of the class declaration. This adds documentation value and makes things more readable.

**Comment by MaxKellermann** [comment]
>     * It's a cool feature that looks promising and I look forward on having it integrated into AAT.

Great!

>     * How will the users location and/or track be accessible? Trough a web interface or inside the MapView?

First by an OpenLayers-based web interface, which I've started working on. But later, it might be interesting to see your friends on the AAT map.

>     * Protocol specif code needs some documentation: not everyone knows what CRC is and how it is used.

Of course.

>     * `client = new BeaconClient(new InetSocketAddress("138.201.185.127", 5598));`
>       Use constants for the server address and the port number and place them at the beginning of the class declaration. This adds documentation value and makes things more readable.

Very true. Those shall not be hard-coded anyway, but might be presented as default configuration values, so either way, this is the wrong place to have this IP address (which will be a host name later, resolved with DNS, so I can move the server and only change DNS, and of course make it available via IPv6). I may run a public server, but I want anybody to be able to run his own server, either with my (free) software or with a reimplementation. Everybody's freedom is very important to me, even if nobody but me cares.

I guess I'll have a "somewhat working" server next week, and then I'll test this with my wife on my daily rides. This PR will evolve and improve incrementally.

**Comment by MaxKellermann** [comment]
Last week, I've successfully tested this feature, but I havn't improved the code in this PR yet. That will happen soon.
The recent force-push is a rebase and I've moved the `BeaconClient` library to my [Beacon git repository](https://github.com/MaxKellermann/beacon), to be used by Gradle as a ["source dependency"](https://blog.gradle.org/introducing-source-dependencies).

**Comment by MaxKellermann** [comment]
>     * What use will `BeaconSource` have? Right now it only copies `CurrentLocationSource`

I'm not sure what the meaning those `*Source` classes is. I'm still trying to understand the code structure.

Right now, it's the only place which calls `getBeaconService()`; i.e. without it, nobody will ever instantiate the Beacon client. Because nobody is interested in the Beacon client, because nobody knows about it...

Apparently, `OneService` is the central code location which does lazy initialization of all those services, but only of those services which are queried at least one.

How shall I trigger the `BeaconService` instantiation without forcing it through `BeaconSource`?

**Comment by bailuk** [comment]
[`Dispatcher`](https://github.com/bailuk/AAT/blob/master/app/src/main/java/ch/bailu/aat/dispatcher/Dispatcher.java) connects [`ContentSource`](https://github.com/bailuk/AAT/blob/master/app/src/main/java/ch/bailu/aat/dispatcher/ContentSource.java) with [`OnContentUpdatedInterface`](https://github.com/bailuk/AAT/blob/master/app/src/main/java/ch/bailu/aat/dispatcher/OnContentUpdatedInterface.java).

For example `TrackerSource` sends updates from `TrackerService` to Views that implement `OnContentUpdatedInterface` such as `MapView`, `CockpitView` etc... to display an up to date version of the current track.

This is usually the place where services are getting initialized because ConentSource is some sort of layer between a service and the UI.

So I was wondering what type of information you want to propagate to UI-Elements. For example the location of different Beacons or status information about server connection.

**Comment by bailuk** [comment]
If you move the server address to app preferences with an explanation of this feature it would help me to merge this request.

You can subclass `SolidString` (take a look at existing sub-classes for documentation) and add an entry to `GeneralPreferencesView`.

**Comment by MaxKellermann** [comment]
> This is usually the place where services are getting initialized because ConentSource is some sort of layer between a service and the UI.

What if there was no UI interest in the `BeaconService` - it would never be instantiated, would it?
Right now, `BeaconService` is an invisible background service with data going out but not in, and the only connection to the UI is its configuration page (which I'll implement soon). But having to open the configuration page just to get the `BeaconClient` running sounds wrong to me.

**Comment by bailuk** [comment]
> What if there was no UI interest in the BeaconService - it would never be instantiated, would it?

You can just instantiate this service by calling `scontext.getBeaconService()` anyplace.
But I would leave it that way. Sooner or later you would implement some UI feedback anyway. And if it's just some status information.

**Pull request closed without merging**
